package knightswap.gui.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import knightswap.data.PlayerScore;
import knightswap.data.ScoreBoardManager;
import knightswap.gui.KnightSwapApplication;
import org.tinylog.Logger;

import knightswap.KnightSwapState;
import knightswap.utils.PieceType;
import knightswap.utils.Position;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Controller for the main KnightSwap game board graphical user interface.
 * Manages user input, updates the visual game state, and interacts with the game logic
 * provided by {@link KnightSwapState}.
 */
public class KnightSwapController {
    @FXML private Label currentScoreLabel;
    @FXML private Label bestScoreLabel;
    @FXML private Label statusLabel;
    @FXML private Button button00;
    @FXML private Button button01;
    @FXML private Button button02;
    @FXML private Button button10;
    @FXML private Button button11;
    @FXML private Button button12;
    @FXML private Button button20;
    @FXML private Button button21;
    @FXML private Button button22;
    @FXML private Button button30;
    @FXML private Button button31;
    @FXML private Button button32;

    private int movesMade;
    private static String playerName;
    private Button[][] buttons;
    private Button firstClickButton = null;
    private Position firstClickPosition = null;

    private KnightSwapState gameState;

    private final Map<Button, String> originalStyles = new HashMap<>();

    private static final String DARK_SQUARE_STYLE = "-fx-background-color: #A0522D; -fx-background-radius: 0;";
    private static final String LIGHT_SQUARE_STYLE = "-fx-background-color: #FFF8DC; -fx-background-radius: 0;";
    private static final String HIGHLIGHT_STYLE = "-fx-background-color: #6B4226; -fx-background-radius: 0; -fx-border-color: yellow; -fx-border-width: 2;";

    /**
     * Constructs a new {@code KnightSwapController}.
     * This constructor is invoked by the FXML loader.
     */
    public KnightSwapController() {}

    /**
     * Initializes the controller after all {@code @FXML} annotated fields are injected.
     * Sets up the chessboard GUI, initializes the {@link KnightSwapState}, and updates initial display elements.
     */
    @FXML
    public void initialize() {
        if (playerName == null || playerName.isEmpty()) {
            playerName = "Guest";
            Logger.warn("Player name not retrieved, defaulting to 'Guest'.");
        } else {
            Logger.info("Player name set to: {}", playerName);
        }

        movesMade = 0;
        gameState = new KnightSwapState();

        buttons = new Button[][] {
                { button00, button01, button02 },
                { button10, button11, button12 },
                { button20, button21, button22 },
                { button30, button31, button32 }
        };

        for (int row = 0; row < 4; row++) {
            for (int col = 0; col < 3; col++) {
                Button btn = buttons[row][col];
                btn.setFont(Font.font("Segoe UI Symbol", 45));

                btn.setOnAction(this::handleButtonClick);

                if ((row + col) % 2 == 0) {
                    originalStyles.put(btn, DARK_SQUARE_STYLE);
                } else {
                    originalStyles.put(btn, LIGHT_SQUARE_STYLE);
                }
            }
        }

        updateBoard();
        updateScoreAndStatusLabels();
    }

    /**
     * Handles click events on the chessboard buttons.
     * Implements a two-click selection mechanism: the first click selects a piece,
     * and the second click attempts to move it to a new square.
     *
     * @param event The {@link ActionEvent} generated by the button click.
     */
    @FXML
    private void handleButtonClick(ActionEvent event) {
        Button clickedButton = (Button) event.getSource();
        int clickedRow = GridPane.getRowIndex(clickedButton) == null ? 0 : GridPane.getRowIndex(clickedButton);
        int clickedCol = GridPane.getColumnIndex(clickedButton) == null ? 0 : GridPane.getColumnIndex(clickedButton);
        Position clickedPosition = new Position(clickedRow, clickedCol);

        Logger.debug("Button clicked at ({}, {})", clickedRow, clickedCol);

        if (firstClickButton == null) {
            char pieceAtClickedPos = gameState.getPieceAt(clickedRow, clickedCol);

            if ((gameState.getCurrentPlayer() == PieceType.LIGHT && pieceAtClickedPos == PieceType.LIGHT.getSymbol()) ||
                    (gameState.getCurrentPlayer() == PieceType.DARK && pieceAtClickedPos == PieceType.DARK.getSymbol())) {

                firstClickButton = clickedButton;
                firstClickPosition = clickedPosition;
                firstClickButton.setStyle(HIGHLIGHT_STYLE);
                statusLabel.setText("Selected: (" + clickedRow + ", " + clickedCol + "). Choose target.");
                Logger.info("Piece selected at ({}, {}). Current player: {}", clickedRow, clickedCol, gameState.getCurrentPlayer());
            } else if (pieceAtClickedPos == '.') {
                statusLabel.setText("Empty square! Select a piece.");
                Logger.warn("Clicked on empty square at ({}, {}). No piece selected.", clickedRow, clickedCol);
            } else {
                statusLabel.setText("Not your piece! (" + gameState.getCurrentPlayer() + " to move)");
                Logger.warn("Clicked on opponent's piece ({}) at ({}, {}).", pieceAtClickedPos, clickedRow, clickedCol);
            }
        } else {
            if (clickedButton == firstClickButton) {
                firstClickButton.setStyle(originalStyles.get(firstClickButton));
                firstClickButton = null;
                firstClickPosition = null;
                statusLabel.setText("Selection cancelled.");
                Logger.info("Selection at ({}, {}) cancelled.", clickedRow, clickedCol);
            }
            else {
                String moveString = String.format("%d %d %d %d",
                        firstClickPosition.row(), firstClickPosition.col(),
                        clickedPosition.row(), clickedPosition.col());

                if (gameState.isLegalMove(moveString)) {
                    gameState.makeMove(moveString);
                    movesMade++;
                    Logger.info("Move made: {}.", moveString);

                    firstClickButton.setStyle(originalStyles.get(firstClickButton));
                    firstClickButton = null;
                    firstClickPosition = null;

                    updateBoard();
                    updateScoreAndStatusLabels();

                    if (gameState.isSolved()) {
                        statusLabel.setText("Congratulations! Puzzle solved.");
                        Logger.info("KnightSwap puzzle solved!");
                        disableAllButtons();

                        ScoreBoardManager manager = KnightSwapApplication.getScoreBoardManager();
                        if (manager != null) {
                            manager.addOrUpdatePlayerScore(playerName, movesMade);
                            updateScoreAndStatusLabels();
                        } else {
                            Logger.error("ScoreBoardManager is null, cannot save score for player {}.", playerName);
                        }
                    }
                } else {
                    Logger.warn("Illegal move attempted from ({}, {}) to ({}, {}).",
                            firstClickPosition.row(), firstClickPosition.col(),
                            clickedRow, clickedCol);
                    statusLabel.setText("Invalid move! Try again.");
                    firstClickButton.setStyle(originalStyles.get(firstClickButton));
                    firstClickButton = null;
                    firstClickPosition = null;
                }
            }
        }
    }

    /**
     * Displays the help screen with game solution steps.
     * The current game board window is hidden when the help screen appears.
     *
     * @param event The {@link ActionEvent} triggered by the "Help" button.
     * @throws IOException If the FXML for the help screen cannot be loaded.
     */
    public void showHelpScreen(ActionEvent event) throws IOException {
        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        KnightSwapApplication.showHelpScreen(currentStage);
    }

    /**
     * Displays the leaderboard screen.
     * The current game board window is hidden when the leaderboard screen appears.
     *
     * @param event The {@link ActionEvent} triggered by the "Leaderboard" button.
     * @throws IOException If the FXML for the leaderboard screen cannot be loaded.
     */
    public void showLeaderBoard(ActionEvent event) throws IOException {
        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        KnightSwapApplication.showLeaderBoard(currentStage);
    }

    /**
     * Resets the game board to its initial configuration and resets the move counter.
     * This method is called when the "Reset" button is clicked.
     */
    @FXML
    private void handleResetButton() {
        movesMade = 0;
        gameState = new KnightSwapState();
        firstClickButton = null;
        firstClickPosition = null;

        enableAllButtons();

        updateBoard();
        updateScoreAndStatusLabels();
        Logger.info("Game board reset successful. Moves reset to 0.");
    }

    /**
     * Updates the visual appearance of the chessboard based on the current {@link KnightSwapState}.
     * Sets the correct piece symbols and square colors for all buttons.
     */
    private void updateBoard() {
        for (int row = 0; row < 4; row++) {
            for (int col = 0; col < 3; col++) {
                char pieceChar = gameState.getPieceAt(row, col);
                String pieceSymbol;

                if (pieceChar == PieceType.LIGHT.getSymbol()) {
                    pieceSymbol = "♘";
                } else if (pieceChar == PieceType.DARK.getSymbol()) {
                    pieceSymbol = "♞";
                } else {
                    pieceSymbol = "";
                }
                buttons[row][col].setText(pieceSymbol);
                buttons[row][col].setStyle(originalStyles.get(buttons[row][col]));
            }
        }

        if (firstClickButton != null) {
            firstClickButton.setStyle(HIGHLIGHT_STYLE);
        }
    }

    /**
     * Updates the {@code currentScoreLabel}, {@code bestScoreLabel}, and {@code statusLabel}
     * with current game information.
     * Displays the current player's turn, moves made, and the player's best score.
     */
    private void updateScoreAndStatusLabels() {
        if (gameState.isSolved()) {
            statusLabel.setText("Congratulations! Puzzle solved.");
        } else {
            statusLabel.setText(String.format("%s to move.", gameState.getCurrentPlayer() == PieceType.LIGHT ? "Light" : "Dark"));
        }

        currentScoreLabel.setText(String.valueOf(movesMade));

        ScoreBoardManager manager = KnightSwapApplication.getScoreBoardManager();
        if (manager != null && playerName != null && !playerName.isEmpty()) {
            Optional<PlayerScore> bestScore = manager.getPlayerScore(playerName);
            if (bestScore.isPresent()) {
                bestScoreLabel.setText(String.valueOf(bestScore.get().getBestScore()));
            } else {
                bestScoreLabel.setText("0");
            }
        } else {
            bestScoreLabel.setText("0");
            if (manager == null) Logger.error("ScoreBoardManager is null when updating best score label.");
            if (playerName == null || playerName.isEmpty()) Logger.warn("Player name is not set when updating best score label.");
        }
    }

    /**
     * Disables all chessboard buttons, preventing further interaction.
     * This is typically used when the puzzle is solved.
     */
    private void disableAllButtons() {
        for (int row = 0; row < 4; row++) {
            for (int col = 0; col < 3; col++) {
                buttons[row][col].setDisable(true);
            }
        }
    }

    /**
     * Enables all chessboard buttons, allowing user interaction.
     * This is typically used when resetting the puzzle.
     */
    private void enableAllButtons() {
        for (int row = 0; row < 4; row++) {
            for (int col = 0; col < 3; col++) {
                buttons[row][col].setDisable(false);
            }
        }
    }

    /**
     * Sets the name of the current player. This static method is typically called
     * from another controller (e.g., a login or start screen) to set the player's identity
     * before the game board is initialized.
     *
     * @param name The {@link String} name of the player.
     */
    public static void setPlayerName(String name) {
        playerName = name;
    }
}